CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(50) DEFAULT 'USER'
);

CREATE TABLE ai_requests (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                             input_text TEXT,
                             ai_response TEXT,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);