-- 1. Создаем таблицу университетов
CREATE TABLE universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    short_name VARCHAR(255),
    type VARCHAR(255),
    price VARCHAR(255),
    rating DOUBLE PRECISION,
    location VARCHAR(255),
    image_url VARCHAR(500),
    description TEXT,
    contacts VARCHAR(255),
    website VARCHAR(255),
    military BOOLEAN DEFAULT FALSE,
    dorm BOOLEAN DEFAULT FALSE,
    focus VARCHAR(255)
);

-- 2. Создаем таблицу для списка программ
CREATE TABLE university_programs (
    university_id BIGINT REFERENCES universities(id) ON DELETE CASCADE,
    program_name VARCHAR(255)
);

-- 3. Вставляем данные (Точь-в-точь как на твоем фронте)

-- IITU
INSERT INTO universities (name, short_name, type, price, rating, location, image_url, description, contacts, website, military, dorm, focus)
VALUES ('International Information Technology University', 'IITU (МУИТ)', 'IT & Инжиниринг', '1 200 000 ₸', 4.9, 'Алматы, ул. Манаса 34/1',
        'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
        'МУИТ — ведущий специализированный IT-университет Центральной Азии. Вуз формирует цифровую элиту страны, сотрудничает с Apple, Microsoft, Huawei.',
        '+7 (727) 320 00 00', 'www.iitu.kz', TRUE, TRUE, 'IT & Engineering');

INSERT INTO university_programs (university_id, program_name) VALUES
((SELECT id FROM universities WHERE short_name='IITU (МУИТ)'), 'Computer Science'),
((SELECT id FROM universities WHERE short_name='IITU (МУИТ)'), 'Cybersecurity'),
((SELECT id FROM universities WHERE short_name='IITU (МУИТ)'), 'Software Engineering'),
((SELECT id FROM universities WHERE short_name='IITU (МУИТ)'), 'Big Data Analysis');

-- KBTU
INSERT INTO universities (name, short_name, type, price, rating, location, image_url, description, contacts, website, military, dorm, focus)
VALUES ('Kazakh-British Technical University', 'KBTU (КБТУ)', 'Технический', '1 800 000 ₸', 4.8, 'Алматы, ул. Толе би 59',
        'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
        'КБТУ — лидер технического образования. Программы двойного диплома с Лондонской школой экономики. Сильнейшие связи с нефтегазовым сектором.',
        '+7 (727) 357 42 42', 'www.kbtu.kz', TRUE, TRUE, 'Oil & Gas, IT');

INSERT INTO university_programs (university_id, program_name) VALUES
((SELECT id FROM universities WHERE short_name='KBTU (КБТУ)'), 'Petroleum Engineering'),
((SELECT id FROM universities WHERE short_name='KBTU (КБТУ)'), 'Information Systems'),
((SELECT id FROM universities WHERE short_name='KBTU (КБТУ)'), 'Business School');

-- SDU
INSERT INTO universities (name, short_name, type, price, rating, location, image_url, description, contacts, website, military, dorm, focus)
VALUES ('Suleyman Demirel University', 'SDU (СДУ)', 'Гуманитарно-Tech', '1 400 000 ₸', 4.7, 'Каскелен, Алматинская обл.',
        'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80',
        'СДУ — современный кампус, англоязычное обучение и сильная корпоративная культура. Один из самых быстрорастущих университетов.',
        '+7 (727) 307 95 65', 'sdu.edu.kz', TRUE, TRUE, 'General & Tech');

INSERT INTO university_programs (university_id, program_name) VALUES
((SELECT id FROM universities WHERE short_name='SDU (СДУ)'), 'Computer Engineering'),
((SELECT id FROM universities WHERE short_name='SDU (СДУ)'), 'Law'),
((SELECT id FROM universities WHERE short_name='SDU (СДУ)'), 'Mathematics');

-- KazNU
INSERT INTO universities (name, short_name, type, price, rating, location, image_url, description, contacts, website, military, dorm, focus)
VALUES ('Al-Farabi Kazakh National University', 'KazNU (КазНУ)', 'Исследовательский', '1 000 000 ₸', 4.6, 'Алматы, пр. Аль-Фараби 71',
        'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
        'Главный национальный вуз страны. Огромный кампус (Казгуград), фундаментальная наука и более 100 специальностей.',
        '+7 (727) 377 33 33', 'kaznu.kz', TRUE, TRUE, 'Science & History');

INSERT INTO university_programs (university_id, program_name) VALUES
((SELECT id FROM universities WHERE short_name='KazNU (КазНУ)'), 'Physics'),
((SELECT id FROM universities WHERE short_name='KazNU (КазНУ)'), 'Chemistry');